### ISSUE TITLE
Cannot find module "memdown"

### ISSUE THREAD

**Issue by stevenroose** [smartcontractproduction/sol-unit#13]
```
$ solunit

module.js:340
    throw err;
          ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sol-unit/node_modules/merkle-patricia-tree/baseTrie.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I tried `sudo npm install memdown` and `sudo npm install memdown --global`, but I still get this error.

**Comment by stevenroose** [comment]
In the meantime, I tried upgrading to the most recent version of Node and NPM (Ubuntu provides very old ones) and removing and reinstalling all modules again, but I get the same error.

**Comment by stevenroose** [comment]
Solved.
