### ISSUE TITLE
ethereumjs-vm version issues

### ISSUE THREAD

**Issue by androlo** [smartcontractproduction/sol-unit#9]
works on 15.04 but throws assertion error on 14.04. 

```
Running tests for:  0=ArrayTest, 1=BankTest, 2=BasicTypesTest, 3=CoinTest, 4=DemoTest, 5=GlobalsTest, 6=IndirectionTest, 7=StructsTest, 8=WrapsInternalTest

Starting: ArrayTest
Deploying contract.


assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at Object.exports.pubToAddress.exports.publicToAddress (/home/andreas/WebstormProjects/sol-unit/node_modules/ethereumjs-util/index.js:307:3)
    at Program.init (/home/andreas/WebstormProjects/sol-unit/lib/chain/program.js:38:25)
    at TestRunner.run (/home/andreas/WebstormProjects/sol-unit/lib/test_runner.js:97:10)
    at SUnit.runContract (/home/andreas/WebstormProjects/sol-unit/lib/sol_unit.js:138:10)
    at SUnit.start (/home/andreas/WebstormProjects/sol-unit/lib/sol_unit.js:71:10)
    at main (/home/andreas/WebstormProjects/sol-unit/bin/solunit.js:126:11)
    at Object.<anonymous> (/home/andreas/WebstormProjects/sol-unit/bin/solunit.js:20:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

```

**Comment by androlo** [comment]
Potential ethereumjs issue (tests fail). 

https://github.com/ethereumjs/ethereumjs-vm/issues/35

**Comment by androlo** [comment]
Yep. Fails on 15.04 too with latest. Just gonna wait this out, since there are no known users of this lib yet, and dao-framework hasn't been formally announced.

**Comment by androlo** [comment]
evm js fixed.
